extra_arguments:
  feature_extractor:
    SiftExtraction.use_gpu: 0
  sequential_matcher:
    SequentialMatching.overlap: 15
    SequentialMatching.quadratic_overlap: 1
    SiftMatching.use_gpu: 0
    SiftMatching.guided_matching: 1
  exhaustive_matcher:
    SiftMatching.use_gpu: 0
    SiftMatching.guided_matching: 1
  mapper:
    Mapper.ba_refine_focal_length: 1
    Mapper.ba_refine_principal_point: 0
    Mapper.ba_refine_extra_params: 1
