from __future__ import annotations

import json
from pathlib import Path

import pytest

from teleop_rearchitecture.unified_evaluator import (
    PERIOD_NS,
    build_time_grid,
    causal_target_index,
    evaluate_unified_fixture,
    load_accepted_joint_targets,
    render_benchmark_markdown_rows,
)


FIXTURE = Path(
    "docs/history/incidents/quest_jaka_20260722_23/measurements/"
    "jaka_edg_sim_initial_accepted_targets_20260722.jsonl"
)
MODEL = Path("data/sim_assets/jaka_rh56.xml")
CHECKED_BENCHMARK = Path(
    "docs/research/teleop_rearchitecture/results/unified_benchmark.json"
)
CHECKED_TABLE = Path(
    "docs/research/teleop_rearchitecture/results/unified_benchmark_table.md"
)


def test_unified_input_preserves_accepted_joint_target_contract() -> None:
    fixture = load_accepted_joint_targets(FIXTURE)
    assert len(fixture.targets) == 55
    assert fixture.targets[0].sequence == 1
    assert fixture.targets[0].accepted is True
    assert fixture.targets[0].output_applied is True
    assert fixture.targets[0].target_state == "ACTIVE"
    assert fixture.sha256 == "04309b70214b7d48709e729fed1f8c6955c6bdda2c4ac72ae6a8919f15dfe663"
    assert fixture.timestamp_monotonic is True


def test_common_grid_is_exact_and_causal_target_never_uses_future() -> None:
    fixture = load_accepted_joint_targets(FIXTURE)
    grid = build_time_grid(fixture)
    assert grid.active_ns[0] == fixture.targets[0].control_monotonic_ns
    assert grid.active_ns[-1] >= fixture.targets[-1].control_monotonic_ns
    assert causal_target_index(fixture.targets, grid.active_ns[-1]) == len(fixture.targets) - 1
    assert all(right - left == PERIOD_NS for left, right in zip(grid.active_ns, grid.active_ns[1:]))
    for tick_ns in grid.active_ns:
        index = causal_target_index(fixture.targets, tick_ns)
        assert fixture.targets[index].control_monotonic_ns <= tick_ns
        if index + 1 < len(fixture.targets):
            assert fixture.targets[index + 1].control_monotonic_ns > tick_ns


def test_unified_schema_has_finite_json_and_all_common_backends() -> None:
    fixture = load_accepted_joint_targets(FIXTURE)
    report = evaluate_unified_fixture(
        fixture,
        model_path=MODEL,
        repository_commit="test-commit",
        working_tree_dirty=True,
        settling_duration_s=0.08,
    )
    assert report["schema_version"] == "teleop_unified_benchmark.v1"
    assert {row["backend"] for row in report["benchmarks"]} == {
        "historical_pre_gate_pwl_emitted_resampled",
        "production_style_pwl_reconstruction",
        "selected_ruckig_position_otg",
        "candidate_b_resolved_rate_reference",
        "candidate_c_position_reference",
    }
    required = {
        "schema_version", "repository_commit", "working_tree_dirty",
        "backend", "fixture", "fixture_sha256", "model", "frame",
        "period_s", "target_reference_semantics", "windows", "tracking",
        "interpolated_tracking", "settling", "dynamics", "command_age",
        "trajectory_shift_estimator", "cpu", "mailbox", "stop", "limitations",
    }
    assert all(required <= set(row) for row in report["benchmarks"])
    json.dumps(report, allow_nan=False)


def test_documentation_rows_are_generated_from_benchmark_records() -> None:
    fixture = load_accepted_joint_targets(FIXTURE)
    report = evaluate_unified_fixture(
        fixture,
        model_path=MODEL,
        repository_commit="test-commit",
        working_tree_dirty=True,
        settling_duration_s=0.08,
        backends=("candidate_b_resolved_rate_reference",),
    )
    rows = render_benchmark_markdown_rows(report)
    assert len(rows) == 1
    assert "candidate_b_resolved_rate_reference" in rows[0]
    assert f"{report['benchmarks'][0]['tracking']['palm_model_command_separation_m']['rms'] * 1000:.3f}" in rows[0]


def test_checked_markdown_table_is_derived_from_checked_json() -> None:
    payload = json.loads(CHECKED_BENCHMARK.read_text(encoding="utf-8"))
    rows = [
        row
        for report in payload["reports"]
        for row in render_benchmark_markdown_rows(report)
    ]
    expected = "\n".join(
        [
            "<!-- Generated by tools/run_teleop_unified_benchmark.py; do not hand edit. -->",
            "",
            "| Fixture | Backend | causal position RMS mm | causal orientation RMS mrad | interpolated position RMS mm | interpolated orientation RMS mrad |",
            "| --- | --- | ---: | ---: | ---: | ---: |",
            *rows,
            "",
        ]
    )
    assert CHECKED_TABLE.read_text(encoding="utf-8") == expected


def test_non_monotonic_fixture_fails_closed(tmp_path: Path) -> None:
    bad = tmp_path / "bad.jsonl"
    rows = [
        {"accepted": True, "output_applied": True, "accepted_target_sequence": 1, "control_monotonic_ns": 10, "accepted_joint_target_rad": [0.0] * 6},
        {"accepted": True, "output_applied": True, "accepted_target_sequence": 2, "control_monotonic_ns": 10, "accepted_joint_target_rad": [0.1] * 6},
    ]
    bad.write_text("\n".join(json.dumps(row) for row in rows), encoding="utf-8")
    with pytest.raises(ValueError, match="timestamps must increase"):
        load_accepted_joint_targets(bad)
