"""Device-independent Motion Input Platform (UMIP)."""

from .diagnostics import StreamingDiagnostics
from .clutch import (
    AnalogClutchSample,
    AnalogHoldToRun,
    ArmClutchMachine,
    ArmClutchState,
    ClutchAction,
    HandClutchMachine,
    HandClutchState,
)
from .controller_protocol import (
    CTRL_FIELD_NAMES,
    CTRL_PACKET_PREFIX,
    CTRL_PROTOCOL_VERSION,
    ControllerPacket,
    ControllerPacketError,
    QuestTransportKind,
    QuestTransportPacket,
    parse_controller_datagram,
    parse_controller_line,
    parse_quest_transport_datagram,
)
from .controller_provider import (
    ControllerClutchAdapter,
    ControllerClutchFrame,
    ControllerProvider,
    ControllerProviderState,
    TransportClutchMonitor,
    TransportClutchSnapshot,
)
from .errors import (
    MotionInputError,
    ProtocolValidationError,
    ProviderStateError,
    SerializationError,
    SourceDisconnected,
)
from .frames import FrameDefinition, FrameRegistry, Handedness
from .hts_canonical import (
    CANONICAL_OPERATOR_FRAME,
    FUTURE_ROBOT_BASE_FRAME,
    LEFT_WRIST_FRAME,
    QUEST_HEAD_FRAME,
    QUEST_WORLD_FRAME,
    RIGHT_WRIST_FRAME,
    CanonicalQuestState,
    ClutchState,
    FutureTeleopInput,
    HtsCanonicalAssembler,
    QuestHandObservation,
    QuestHeadObservation,
    QuestJointObservation,
    SourceSequenceTracker,
    prepare_inactive_future_input,
)
from .hts_gate import evaluate_required_right_hand_recording
from .hts_operator import (
    OfflineOperatorTarget,
    OperatorInputState,
    OperatorStateTransition,
    RightHandOperatorConfig,
    RightHandOperatorPipeline,
)
from .hts_protocol import (
    HTS_DEFAULT_UDP_PORT,
    HTS_JOINT_NAMES,
    HTS_MAX_DATAGRAM_BYTES,
    HTS_PROTOCOL_VERSION,
    HtsHeadPosePacket,
    HtsLandmarksPacket,
    HtsPacketKind,
    HtsWristPacket,
    normalize_quaternion,
    parse_hts_datagram,
    parse_hts_line,
)
from .hts_telemetry import HtsTelemetry
from .hts_transport import (
    HtsRawRecordingReader,
    HtsRawRecordingWriter,
    HtsUdpReceiver,
    ReceivedHtsDatagram,
    inspect_datagram,
    replay_datagrams,
)
from .model import (
    DeviceDescriptor,
    GestureSample,
    HandArticulation,
    JointSample,
    MotionInputSample,
    MotionKind,
    Pose6D,
    Side,
    Timestamp,
    TrackingState,
    UMIP_VERSION,
)
from .provider import MotionInputProvider, ProviderState
from .quest import QuestMotionProvider, UdpQuestSource
from .recording import MotionRecordingReader, MotionRecordingWriter
from .replay import ReplayMode, ReplayProvider

__all__ = [
    "AnalogClutchSample",
    "AnalogHoldToRun",
    "ArmClutchMachine",
    "ArmClutchState",
    "CANONICAL_OPERATOR_FRAME",
    "CanonicalQuestState",
    "ClutchAction",
    "ClutchState",
    "ControllerClutchAdapter",
    "ControllerClutchFrame",
    "ControllerPacket",
    "ControllerPacketError",
    "ControllerProvider",
    "ControllerProviderState",
    "CTRL_FIELD_NAMES",
    "CTRL_PACKET_PREFIX",
    "CTRL_PROTOCOL_VERSION",
    "DeviceDescriptor",
    "FrameDefinition",
    "FrameRegistry",
    "FUTURE_ROBOT_BASE_FRAME",
    "FutureTeleopInput",
    "GestureSample",
    "HandArticulation",
    "Handedness",
    "HTS_DEFAULT_UDP_PORT",
    "HTS_JOINT_NAMES",
    "HTS_MAX_DATAGRAM_BYTES",
    "HTS_PROTOCOL_VERSION",
    "HtsCanonicalAssembler",
    "HtsHeadPosePacket",
    "HtsLandmarksPacket",
    "HtsPacketKind",
    "HtsRawRecordingReader",
    "HtsRawRecordingWriter",
    "HtsTelemetry",
    "HtsUdpReceiver",
    "HtsWristPacket",
    "HandClutchMachine",
    "HandClutchState",
    "JointSample",
    "LEFT_WRIST_FRAME",
    "MotionInputError",
    "MotionInputProvider",
    "MotionInputSample",
    "MotionKind",
    "MotionRecordingReader",
    "MotionRecordingWriter",
    "Pose6D",
    "OfflineOperatorTarget",
    "OperatorInputState",
    "OperatorStateTransition",
    "ProtocolValidationError",
    "ProviderState",
    "ProviderStateError",
    "QuestMotionProvider",
    "QuestTransportKind",
    "QuestTransportPacket",
    "QUEST_HEAD_FRAME",
    "QUEST_WORLD_FRAME",
    "QuestHandObservation",
    "QuestHeadObservation",
    "QuestJointObservation",
    "ReceivedHtsDatagram",
    "ReplayMode",
    "ReplayProvider",
    "RIGHT_WRIST_FRAME",
    "RightHandOperatorConfig",
    "RightHandOperatorPipeline",
    "SerializationError",
    "Side",
    "SourceDisconnected",
    "SourceSequenceTracker",
    "StreamingDiagnostics",
    "Timestamp",
    "TransportClutchMonitor",
    "TransportClutchSnapshot",
    "TrackingState",
    "UMIP_VERSION",
    "UdpQuestSource",
    "evaluate_required_right_hand_recording",
    "inspect_datagram",
    "normalize_quaternion",
    "parse_controller_datagram",
    "parse_controller_line",
    "parse_hts_datagram",
    "parse_hts_line",
    "parse_quest_transport_datagram",
    "prepare_inactive_future_input",
    "replay_datagrams",
]
