#!/usr/bin/env python3
from __future__ import annotations

import argparse
import importlib.metadata
import json
import os
import platform
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from digital_twin.io import write_json


COMMANDS = ["ffmpeg", "ffprobe", "colmap", "docker", "conda", "mamba", "pip", "uv", "apt-get", "poetry", "nvidia-smi", "nvcc", "nerfstudio", "ns-train"]
PACKAGES = ["opencv-python", "opencv-contrib-python", "open3d", "trimesh", "numpy", "scipy", "torch", "pycolmap", "nerfstudio", "gsplat", "nerfacc", "diff-gaussian-rasterization", "mujoco", "imageio", "glfw", "PyOpenGL"]


def _version(name: str) -> str | None:
    try:
        return importlib.metadata.version(name)
    except importlib.metadata.PackageNotFoundError:
        return None


def audit_environment() -> dict[str, Any]:
    command_paths = {name: shutil.which(name) for name in COMMANDS}
    packages = {name: _version(name) for name in PACKAGES}
    gpu: dict[str, Any] = {"nvidia_smi_available": bool(command_paths["nvidia-smi"]), "cuda_visible_devices": os.environ.get("CUDA_VISIBLE_DEVICES")}
    if command_paths["nvidia-smi"]:
        process = subprocess.run([command_paths["nvidia-smi"], "--query-gpu=name,driver_version,memory.total", "--format=csv,noheader"], capture_output=True, text=True)
        gpu["nvidia_smi_summary"] = process.stdout.strip() if process.returncode == 0 else None
    torch_info: dict[str, Any] = {"installed": packages["torch"] is not None, "cuda_available": None, "mps_available": None}
    if packages["torch"]:
        try:
            import torch
            torch_info.update(cuda_available=bool(torch.cuda.is_available()), mps_available=bool(getattr(torch.backends, "mps", None) and torch.backends.mps.is_available()))
        except Exception as exc:  # environment audit must survive broken binary installs
            torch_info["import_error"] = f"{type(exc).__name__}: {exc}"
    system = platform.system()
    machine = platform.machine()
    report = {
        "operating_system": {"system": system, "release": platform.release(), "version": platform.version()},
        "cpu_architecture": machine,
        "python": {"version": platform.python_version(), "executable": sys.executable},
        "package_managers": {name: command_paths.get(name) for name in ("pip", "uv", "apt-get", "poetry", "conda", "mamba", "docker")},
        "commands": command_paths,
        "python_packages": packages,
        "gpu": gpu,
        "torch": torch_info,
        "apple_silicon": system == "Darwin" and machine in {"arm64", "aarch64"},
        "metal_or_mps_support": torch_info["mps_available"],
        "simulation_engine": {"primary": "MuJoCo" if packages["mujoco"] else None},
        "rendering_dependencies": {"opencv": packages["opencv-python"] or packages["opencv-contrib-python"], "mujoco": packages["mujoco"], "open3d": packages["open3d"], "trimesh": packages["trimesh"], "imageio": packages["imageio"], "glfw": packages["glfw"], "pyopengl": packages["PyOpenGL"]},
    }
    return report


def render_markdown(report: dict[str, Any]) -> str:
    commands = report["commands"]
    packages = report["python_packages"]
    colmap_route = (
        "Use the detected COLMAP executable."
        if commands["colmap"]
        else "COLMAP is unavailable. Prefer an isolated conda environment or documented Docker/external installation; do not alter the project environment."
    )
    gs_route = (
        "An NVIDIA CUDA path is visible; validate versions before training."
        if report["torch"]["cuda_available"]
        else "No usable CUDA/PyTorch training path was detected. Use a separate NVIDIA workstation/container or remote training host for Gaussian Splatting."
    )
    rows = "\n".join(f"| `{name}` | {path or 'missing'} |" for name, path in commands.items())
    package_rows = "\n".join(f"| `{name}` | {version or 'missing'} |" for name, version in packages.items())
    return f"""# Digital-Twin Environment Report

Generated by `tools/digital_twin/check_environment.py`.

## Host

- OS: {report['operating_system']['system']} {report['operating_system']['release']}
- Architecture: {report['cpu_architecture']}
- Python: {report['python']['version']} at `{report['python']['executable']}`
- Apple Silicon: {report['apple_silicon']}; MPS usable: {report['metal_or_mps_support']}
- NVIDIA GPU visible: {report['gpu']['nvidia_smi_available']}; PyTorch CUDA usable: {report['torch']['cuda_available']}

## Commands

| Command | Path/status |
|---|---|
{rows}

## Python packages

| Package | Version/status |
|---|---|
{package_rows}

## Routes and limitations

- Primary simulator: {report['simulation_engine']['primary']}.
- Video metadata: {'ffprobe is available.' if commands['ffprobe'] else 'ffprobe/ffmpeg are missing; OpenCV can decode the capture but cannot provide a complete privacy/VFR/color/audio audit.'}
- Sparse reconstruction: {colmap_route}
- Visual reconstruction: {gs_route}
- Open3D is {'available' if packages['open3d'] else 'not installed; core geometry tools should use NumPy/trimesh and keep Open3D optional'}.

No packages were installed or changed by this audit.
"""


def main() -> None:
    parser = argparse.ArgumentParser(description="Audit reconstruction, simulation, GPU and rendering dependencies without installing anything.")
    parser.add_argument("--json-output", type=Path, default=Path("artifacts/digital_twin/environment_report.json"))
    parser.add_argument("--markdown-output", type=Path, default=Path("artifacts/digital_twin/environment_report.md"))
    parser.add_argument("--dry-run", action="store_true", help="Print the report without writing files.")
    args = parser.parse_args()
    report = audit_environment()
    markdown = render_markdown(report)
    if args.dry_run:
        print(json.dumps(report, indent=2)); return
    write_json(args.json_output, report)
    args.markdown_output.parent.mkdir(parents=True, exist_ok=True)
    args.markdown_output.write_text(markdown, encoding="utf-8")
    print(f"Environment report written to: {args.json_output} and {args.markdown_output}")


if __name__ == "__main__":
    main()
